#pragma once

enum MsgCodes {
	ERROR_CODE = 1, LOGIN_CODE, SIGNUP_CODE, LOGOUT_CODE,
	GET_ROOMS_CODE, GET_PLAYERS_CODE, JOIN_ROOM_CODE,
	CREATE_ROOM_CODE, HIGH_SCORE_CODE, PERSONAL_STATS_CODE,
	CLOSE_ROOM_CODE, START_GAME_CODE, GET_ROOM_STATE_CODE, LEAVE_ROOM
};